/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ar.com.mercadolibre.gradlepractice;

import org.junit.Assert;
import org.junit.Test;
import org.mockito.Mockito;

import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }

    @Test public void testMockito() {
        Integer numero = Mockito.mock(Integer.class);
        Mockito.doReturn(3).when(numero).intValue();
        Assert.assertEquals(3,numero.intValue());

    }

}
